### ISSUE TITLE
Linter crashes when setting extra channels

### ISSUE THREAD

**Issue by Zasco** [memo33/sc4pac#57]
Error message:

> Traceback (most recent call last):
  File "sc4pac-yaml-schema.py", line 502, in <module>
    sys.exit(main())
             ~~~~^^
  File "sc4pac-yaml-schema.py", line 471, in main
    for label, unknown in dependency_checker.unknowns().items():
                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "sc4pac-yaml-schema.py", line 303, in unknowns
    contents = [self._get_channel_contents(channel_url) for channel_url in extra_channels]
                ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "sc4pac-yaml-schema.py", line 296, in _get_channel_contents
    return channel_contents['contents']
           ~~~~~~~~~~~~~~~~^^^^^^^^^^^^
KeyError: 'contents'

The linter was not updated for [_sc4pac_ **0.5.0**](https://github.com/memo33/sc4pac-tools/releases/tag/0.5.0) and scheme **5** of channel contents. This call stack does not happen if no extra channel is set:
https://github.com/memo33/sc4pac/blob/9d6e4443284ee063a1962d3092a4b31bf416f2a7/.github/sc4pac-yaml-schema.py#L180-L183

Replacing
https://github.com/memo33/sc4pac/blob/9d6e4443284ee063a1962d3092a4b31bf416f2a7/.github/sc4pac-yaml-schema.py#L319 and https://github.com/memo33/sc4pac/blob/9d6e4443284ee063a1962d3092a4b31bf416f2a7/.github/sc4pac-yaml-schema.py#L327-L328
by
```python
return channel_contents
```
and
```python
remote_assets = [asset['name'] for channel in contents for asset in channel['assets']]
remote_packages = [f"{pkg['group']}:{pkg['name']}" for channel in contents for pkg in channel['packages']]
```

is the solution I used to fix the problem. I will make a PR soon with this change.

**Comment by memo33** [comment]
Oh, good catch. Thanks. I'm going to work on #29 in the next days, which will move the linter to a central location (and hence out of this and your repository), which should make things easier going forward.

**Comment by Zasco** [comment]
Closed by https://github.com/memo33/sc4pac-actions/commit/43c6be3.
